spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cqrs_db
    username: cqrs
    password: cqrs_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Emit a random policy event every N milliseconds
policy-engine:
  emit-interval-ms: 5000
